language: bash
dist: xenial
sudo: required
env:
  - DOCKER_COMPOSE_VERSION=1.27.4

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -p ci up -d

scripts:
  - docker wait ci_node_app_test_1

after_success:
  - docker-compose down 
  #Log in
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
  - docker buildx inspect --bootstrap
  - docker buildx build --push --platform linux/arm,linux/arm64,linux/amd64 --tag vinaylanka/water-level-api:latest  .